#!/usr/bin/env python3
"""
analyze_labels.py - Analyze label coverage and distribution

Shows what regional, register, temporal, and domain labels we have.
Helps understand what filters we can actually apply.
"""

import json
from pathlib import Path
from collections import Counter
from typing import Dict


def load_metadata(meta_path: Path) -> Dict[str, Dict]:
    """Load metadata JSON."""
    if not meta_path.exists():
        return {}

    with open(meta_path, 'r', encoding='utf-8') as f:
        metadata_list = json.load(f)

    return {entry['word']: entry for entry in metadata_list}


def analyze_labels(metadata: Dict[str, Dict]):
    """Analyze label distribution."""
    # Count entries with each label type
    has_labels = sum(1 for e in metadata.values() if e.get('labels'))
    has_region = sum(1 for e in metadata.values() if e.get('labels', {}).get('region'))
    has_register = sum(1 for e in metadata.values() if e.get('labels', {}).get('register'))
    has_temporal = sum(1 for e in metadata.values() if e.get('labels', {}).get('temporal'))
    has_domain = sum(1 for e in metadata.values() if e.get('labels', {}).get('domain'))

    # Count specific labels
    region_counts = Counter()
    register_counts = Counter()
    temporal_counts = Counter()
    domain_counts = Counter()

    for entry in metadata.values():
        labels = entry.get('labels', {})

        for region in labels.get('region', []):
            region_counts[region] += 1

        for register in labels.get('register', []):
            register_counts[register] += 1

        for temporal in labels.get('temporal', []):
            temporal_counts[temporal] += 1

        for domain in labels.get('domain', []):
            domain_counts[domain] += 1

    # Sample words for each label type
    samples = {
        'region': {},
        'register': {},
        'temporal': {},
        'domain': {},
    }

    for word, entry in metadata.items():
        labels = entry.get('labels', {})

        # Sample 5 words for each label value
        for label_type in ['region', 'register', 'temporal', 'domain']:
            for value in labels.get(label_type, []):
                if value not in samples[label_type]:
                    samples[label_type][value] = []
                if len(samples[label_type][value]) < 5:
                    samples[label_type][value].append(word)

    return {
        'total': len(metadata),
        'has_labels': has_labels,
        'has_region': has_region,
        'has_register': has_register,
        'has_temporal': has_temporal,
        'has_domain': has_domain,
        'region_counts': region_counts,
        'register_counts': register_counts,
        'temporal_counts': temporal_counts,
        'domain_counts': domain_counts,
        'samples': samples,
    }


def generate_report(distribution: str = 'core'):
    """Generate label analysis report."""
    meta_path = Path(f'data/build/{distribution}/{distribution}.meta.json')

    if not meta_path.exists():
        print(f"✗ Metadata not found: {meta_path}")
        print(f"  Run 'make build-{distribution}' first")
        return 1

    metadata = load_metadata(meta_path)
    analysis = analyze_labels(metadata)

    report = f"# Label Coverage Analysis ({distribution.upper()})\n\n"
    report += "Generated by `tools/analyze_labels.py`\n\n"
    report += "Analyzes what labels we have for filtering words by region, register, etc.\n\n"
    report += "---\n\n"

    # Overall coverage
    report += "## Overall Label Coverage\n\n"
    report += f"**Total entries:** {analysis['total']:,}\n\n"

    report += "| Label Type | Entries with Label | Percentage |\n"
    report += "|-----------|-------------------:|-----------:|\n"

    label_types = [
        ('Any labels', 'has_labels'),
        ('Region labels', 'has_region'),
        ('Register labels', 'has_register'),
        ('Temporal labels', 'has_temporal'),
        ('Domain labels', 'has_domain'),
    ]

    for label_name, key in label_types:
        count = analysis[key]
        pct = count / analysis['total'] * 100
        report += f"| {label_name} | {count:,} | {pct:.1f}% |\n"

    report += "\n---\n\n"

    # Regional labels
    if analysis['region_counts']:
        report += "## Regional Labels\n\n"
        report += "Words marked as specific to certain regions/dialects.\n\n"

        report += "| Region | Count | Examples |\n"
        report += "|--------|------:|----------|\n"

        for region, count in analysis['region_counts'].most_common():
            examples = ', '.join(f'`{w}`' for w in analysis['samples']['region'].get(region, [])[:5])
            report += f"| {region} | {count:,} | {examples} |\n"

        report += "\n"
    else:
        report += "## Regional Labels\n\n"
        report += "⚠️ No regional labels found in this distribution.\n\n"

    report += "---\n\n"

    # Register labels
    if analysis['register_counts']:
        report += "## Register Labels\n\n"
        report += "Words marked as informal, vulgar, offensive, etc.\n\n"

        report += "| Register | Count | Examples |\n"
        report += "|----------|------:|----------|\n"

        for register, count in analysis['register_counts'].most_common():
            examples = ', '.join(f'`{w}`' for w in analysis['samples']['register'].get(register, [])[:5])
            report += f"| {register} | {count:,} | {examples} |\n"

        report += "\n"
    else:
        report += "## Register Labels\n\n"
        report += "⚠️ No register labels found in this distribution.\n\n"

    report += "---\n\n"

    # Temporal labels
    if analysis['temporal_counts']:
        report += "## Temporal Labels\n\n"
        report += "Words marked as archaic, obsolete, etc.\n\n"

        report += "| Temporal | Count | Examples |\n"
        report += "|----------|------:|----------|\n"

        for temporal, count in analysis['temporal_counts'].most_common():
            examples = ', '.join(f'`{w}`' for w in analysis['samples']['temporal'].get(temporal, [])[:5])
            report += f"| {temporal} | {count:,} | {examples} |\n"

        report += "\n"
    else:
        report += "## Temporal Labels\n\n"
        report += "⚠️ No temporal labels found in this distribution.\n\n"

    report += "---\n\n"

    # Domain labels
    if analysis['domain_counts']:
        report += "## Domain Labels\n\n"
        report += "Words marked as technical/specialized to certain domains.\n\n"

        report += "| Domain | Count | Examples |\n"
        report += "|--------|------:|----------|\n"

        for domain, count in analysis['domain_counts'].most_common(20):
            examples = ', '.join(f'`{w}`' for w in analysis['samples']['domain'].get(domain, [])[:5])
            report += f"| {domain} | {count:,} | {examples} |\n"

        if len(analysis['domain_counts']) > 20:
            report += f"\n*...and {len(analysis['domain_counts']) - 20} more domains*\n"

        report += "\n"
    else:
        report += "## Domain Labels\n\n"
        report += "⚠️ No domain labels found in this distribution.\n\n"

    report += "---\n\n"

    # Recommendations
    report += "## Filtering Implications\n\n"

    if not analysis['region_counts']:
        report += "### Regional Filtering\n\n"
        report += "**Status:** ❌ Cannot filter by region\n\n"
        report += "This distribution has no regional labels. To exclude British English or other regional variants:\n"
        report += "- Use Plus distribution (Wiktionary has regional labels)\n"
        report += "- Add manual regional tagging\n"
        report += "- Import regional data from external sources\n\n"

    if not analysis['register_counts']:
        report += "### Register Filtering\n\n"
        report += "**Status:** ❌ Cannot filter by register\n\n"
        report += "This distribution has no register labels (informal, vulgar, etc.). To filter offensive words:\n"
        report += "- Use Plus distribution (Wiktionary has register labels)\n"
        report += "- Use manual blocklists\n"
        report += "- Import from external sources\n\n"

    if not analysis['temporal_counts']:
        report += "### Temporal Filtering\n\n"
        report += "**Status:** ❌ Cannot filter by temporal status\n\n"
        report += "This distribution has no temporal labels. To exclude archaic/obsolete words:\n"
        report += "- Use Plus distribution\n"
        report += "- Rely on frequency tiers (archaic words are usually rare)\n\n"

    if not analysis['domain_counts']:
        report += "### Domain Filtering\n\n"
        report += "**Status:** ❌ Cannot filter by domain\n\n"
        report += "This distribution has no domain labels. To exclude technical jargon:\n"
        report += "- Use Plus distribution\n"
        report += "- Rely on frequency tiers\n\n"

    # Write report
    output_path = Path(f'reports/label_analysis_{distribution}.md')
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"✓ Label analysis report written to {output_path}")
    return output_path


if __name__ == '__main__':
    import sys

    distribution = sys.argv[1] if len(sys.argv) > 1 else 'core'

    if distribution not in ['core', 'plus']:
        print(f"Error: distribution must be 'core' or 'plus', got '{distribution}'")
        sys.exit(1)

    generate_report(distribution)
