#!/usr/bin/env python3
"""
inspect_raw.py - Inspect raw downloaded datasets

Generates markdown reports with random samples from the original source files.
Helps verify downloads and understand source data formats.
"""
import json
import random
from pathlib import Path
from typing import List, Dict, Any


def load_jsonl_sample(filepath: Path, n: int = 10) -> List[Dict[str, Any]]:
    """Load random sample of lines from JSONL file."""
    if not filepath.exists():
        return []

    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    sample_size = min(n, len(lines))
    sample_lines = random.sample(lines, sample_size)

    return [json.loads(line) for line in sample_lines]


def count_jsonl_lines(filepath: Path) -> int:
    """Count lines in JSONL file."""
    if not filepath.exists():
        return 0

    with open(filepath, 'r', encoding='utf-8') as f:
        return sum(1 for _ in f)


def inspect_enable() -> str:
    """Inspect ENABLE dataset."""
    filepath = Path('data/raw/core/enable.jsonl')

    if not filepath.exists():
        return "⚠️ ENABLE data not found at `data/raw/core/enable.jsonl`\n"

    count = count_jsonl_lines(filepath)
    sample = load_jsonl_sample(filepath, 5)

    report = f"## ENABLE Dataset\n\n"
    report += f"**Location:** `{filepath}`  \n"
    report += f"**Total entries:** {count:,}\n\n"
    report += "**Sample entries:**\n\n"

    for i, entry in enumerate(sample, 1):
        report += f"{i}. `{entry.get('word', 'N/A')}` - {json.dumps(entry, indent=2)}\n"

    return report


def inspect_eowl() -> str:
    """Inspect EOWL dataset."""
    filepath = Path('data/raw/core/eowl.jsonl')

    if not filepath.exists():
        return "⚠️ EOWL data not found at `data/raw/core/eowl.jsonl`\n"

    count = count_jsonl_lines(filepath)
    sample = load_jsonl_sample(filepath, 5)

    report = f"## EOWL Dataset\n\n"
    report += f"**Location:** `{filepath}`  \n"
    report += f"**Total entries:** {count:,}\n\n"
    report += "**Sample entries:**\n\n"

    for i, entry in enumerate(sample, 1):
        report += f"{i}. `{entry.get('word', 'N/A')}` - {json.dumps(entry, indent=2)}\n"

    return report


def inspect_wiktionary() -> str:
    """Inspect Wiktionary dataset."""
    filepath = Path('data/intermediate/plus/wikt.jsonl')

    if not filepath.exists():
        return "⚠️ Wiktionary data not found at `data/intermediate/plus/wikt.jsonl`\n"

    count = count_jsonl_lines(filepath)
    sample = load_jsonl_sample(filepath, 3)

    report = f"## Wiktionary Dataset\n\n"
    report += f"**Location:** `{filepath}`  \n"
    report += f"**Total entries:** {count:,}\n\n"
    report += "**Sample entries:**\n\n"

    for i, entry in enumerate(sample, 1):
        word = entry.get('word', 'N/A')
        report += f"{i}. `{word}`\n"
        report += "```json\n"
        report += json.dumps(entry, indent=2)
        report += "\n```\n\n"

    return report


def inspect_wordnet() -> str:
    """Inspect WordNet dataset."""
    filepath = Path('data/raw/plus/wordnet.jsonl')

    if not filepath.exists():
        return "⚠️ WordNet data not found at `data/raw/plus/wordnet.jsonl`\n"

    count = count_jsonl_lines(filepath)
    sample = load_jsonl_sample(filepath, 5)

    report = f"## WordNet Dataset\n\n"
    report += f"**Location:** `{filepath}`  \n"
    report += f"**Total entries:** {count:,}\n\n"
    report += "**Sample entries:**\n\n"

    for i, entry in enumerate(sample, 1):
        report += f"{i}. `{entry.get('word', 'N/A')}` - {json.dumps(entry, indent=2)}\n"

    return report


def inspect_frequency() -> str:
    """Inspect frequency dataset."""
    filepath = Path('data/raw/plus/frequency.jsonl')

    if not filepath.exists():
        return "⚠️ Frequency data not found at `data/raw/plus/frequency.jsonl`\n"

    count = count_jsonl_lines(filepath)
    sample = load_jsonl_sample(filepath, 5)

    report = f"## Frequency Dataset\n\n"
    report += f"**Location:** `{filepath}`  \n"
    report += f"**Total entries:** {count:,}\n\n"
    report += "**Sample entries:**\n\n"

    for i, entry in enumerate(sample, 1):
        report += f"{i}. `{entry.get('word', 'N/A')}` - Rank: {entry.get('rank', 'N/A')}\n"

    return report


def generate_report():
    """Generate complete raw data inspection report."""
    random.seed(42)  # Reproducible samples

    report = "# Raw Dataset Inspection Report\n\n"
    report += "Generated by `tools/inspect_raw.py`\n\n"
    report += "This report shows random samples from the original downloaded datasets.\n\n"
    report += "---\n\n"

    report += inspect_enable()
    report += "\n---\n\n"
    report += inspect_eowl()
    report += "\n---\n\n"
    report += inspect_wiktionary()
    report += "\n---\n\n"
    report += inspect_wordnet()
    report += "\n---\n\n"
    report += inspect_frequency()

    # Write report
    output_path = Path('reports/raw_data_inspection.md')
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"✓ Raw data inspection report written to {output_path}")
    return output_path


if __name__ == '__main__':
    generate_report()
